name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET      
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Build
      working-directory: ./src
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./src
      run: dotnet test --no-build --verbosity normal
      
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up DOcker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DOckerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker Image to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./src
        push: true
        tags: user/app:latest
    - name: Image digest
      run: echo $ {{ steps.docker_build.outputs.digest }}
        
        repository: robertohigor/aspnetCoreCrud
        tag_with_ref: true
